Small update for the 1.20 stuff
QuiltMC/quilt-kotlin-template-mod pull request #9
Opened 2023-07-02 05:44 UTC by Fnige

Mostly just forgot to update the quilt.mod.json file when we first did this so now that should basically be the same as the other template mod

- Jesse@Fnige

2023-07-03 19:47 UTC, OroArmor requested changes
Have the gradle dependencies been modified?

2023-07-03 19:47 UTC, OroArmor commented on src/main/resources/quilt.mod.json
> +				"versions": ">=0.19.1"
0.19.2 is out now
```suggestion
				"versions": ">=0.19.2"
```

2023-07-04 02:14 UTC, Fnige commented
If youre talking about the stuff in libs.versions.toml that was already updated, just forgot to do the quilt.mod.json stuff before

2023-07-04 04:20 UTC, OroArmor approved these changes

2023-07-07 03:25 UTC, PotatoPresident approved these changes

2023-07-07 03:25 UTC, merged